services:
  event-service:
    build: ./
    image: event-service
    container_name: event-service
    ports:
      - "8082:8080"
    depends_on:
      - event-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-service-db:5432/event_service_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  event-service-db:
    image: postgres:16.3-alpine
    container_name: event-service-db
    environment:
      - POSTGRES_DB=event_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres