CREATE TABLE events (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    created_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    start_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    location VARCHAR(120) NOT NULL,
    owner_id BIGINT NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);